version: '3.8'

services:
  web:
    build: .
    container_name: hackathon_web
    ports:
      - "8082:80"
    volumes:
      - ./src/frontend:/var/www/html
      - ./src/backend:/var/www/html/backend
      - ./assets:/var/www/html/assets
      - ./vendor:/var/www/html/vendor

    depends_on:
      - db
#CHECK .ENV VS JUST ADDING PASSWORDS
  db:
    image: mysql:5.7
    container_name: hackathon_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hackathon_phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

